[package]
name = "test_call_from_lib"
version = "0.1.0"
edition = "2021"
authors = ["me@mgail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
